# Generated by Django 4.2.7 on 2023-12-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_published'),
        ),
    ]
