# Generated by Django 4.2.7 on 2023-12-27 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0003_notes_delete_description_delete_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['title']},
        ),
    ]
